<?xml version="1.0" encoding="UTF-8"?>
<definitions name="AOI_BankingPartner" targetNamespace="http://www.bercut.com/wsdl/AOI_BankingPartner"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:tns="http://www.bercut.com/wsdl/AOI_BankingPartner" 
	xmlns:ns="http://www.bercut.com/schema/AOI_BankingPartner" 
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	>
    <types>
        <xsd:schema targetNamespace="http://www.bercut.com/wsdl/AOI_BankingPartner" version="1.1">
            <xsd:import namespace="http://www.bercut.com/schema/AOI_BankingPartner" schemaLocation="AOI_BankingPartner.xsd"/>
        </xsd:schema>
    </types>
    <message name="BankingPartnerRequestMessage">
        <part name="parameters" element="ns:notifyPartnerRequest"/>
    </message>
    <message name="BankingPartnerResponseMessage">
        <part name="parameters" element="ns:notifyPartnerResponse"/>
    </message>
    <message name="BankingPartnerFaultMessage">
        <part name="parameters" element="ns:Fault"/>
    </message>
    <portType name="AOI_BankingPartnerPortType">
        <operation name="NotifyPartner">
            <documentation>Операция для осуществления нотификации по факту наступления события (для абонента) в биллинге</documentation>
            <input name="BankingPartnerRequest" message="tns:BankingPartnerRequestMessage"/>
            <output name="BankingPartnerResponse" message="tns:BankingPartnerResponseMessage"/>
            <fault name="BankingPartnerFault" message="tns:BankingPartnerFaultMessage"/>
        </operation>
    </portType>
    <binding name="AOI_BankingPartnerPortTypeBinding" type="tns:AOI_BankingPartnerPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="NotifyPartner">
            <soap:operation/>
            <input name="BankingPartnerRequest">
                <soap:body use="literal"/>
            </input>
            <output name="BankingPartnerResponse">
                <soap:body use="literal"/>
            </output>
            <fault name="BankingPartnerFault">
                <soap:fault use="literal" name="BankingPartnerFault"/>
            </fault>
        </operation>
    </binding>
    <service name="AOI_BankingPartnerService">
        <port name="AOI_BankingPartnerPortTypeBindingPort" binding="tns:AOI_BankingPartnerPortTypeBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/AOI_BankingPartnerService/AOI_BankingPartnerPortTypeBindingPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="AOI_BankingPartner">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="AOI_BankingPartnerPortTypeRole" portType="tns:AOI_BankingPartnerPortType"/>
    </plnk:partnerLinkType>
</definitions>
